# Generated by Django 3.1.3 on 2021-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='owner',
            field=models.ManyToManyField(to='Taxi_Manager.Owner'),
        ),
    ]
