# Generated by Django 3.1.3 on 2021-03-31 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0002_driver_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
