# Generated by Django 3.1.3 on 2021-03-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0004_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact_no',
            field=models.BigIntegerField(unique=True),
        ),
    ]
