# Generated by Django 3.1.3 on 2021-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0007_auto_20210331_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='owner',
        ),
    ]
