# Generated by Django 3.1.3 on 2021-03-31 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0008_remove_driver_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drowsiness',
            name='driver',
        ),
    ]
