# Generated by Django 3.1.3 on 2021-03-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0009_remove_drowsiness_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='taxi_no',
            new_name='taxi',
        ),
    ]
