# Generated by Django 3.1.3 on 2021-03-31 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0010_auto_20210331_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.TimeField(null=True)),
                ('etime', models.TimeField(null=True)),
            ],
        ),
    ]
