# Generated by Django 3.1.3 on 2021-03-31 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0011_drow'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Taxi_Manager.owner'),
        ),
        migrations.AddField(
            model_name='owner',
            name='drivers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Taxi_Manager.driver'),
        ),
    ]
