# Generated by Django 3.1.3 on 2021-03-31 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0012_auto_20210331_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='password',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='username',
        ),
    ]
