# Generated by Django 3.1.3 on 2021-04-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0013_auto_20210331_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drow',
            old_name='etime',
            new_name='drowsiness',
        ),
        migrations.RemoveField(
            model_name='drow',
            name='stime',
        ),
    ]
