# Generated by Django 3.1.3 on 2021-04-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0014_auto_20210402_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drow',
            name='drowsiness',
            field=models.DateTimeField(null=True),
        ),
    ]
