# Generated by Django 3.1.3 on 2021-04-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0015_auto_20210402_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drow',
            name='drowsiness',
            field=models.TimeField(null=True),
        ),
    ]
