# Generated by Django 3.1.3 on 2021-04-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0018_auto_20210402_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='drow',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Taxi_Manager.driver'),
        ),
    ]
