# Generated by Django 3.1.3 on 2021-04-13 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0021_auto_20210413_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='taxi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Taxi_Manager.taxi'),
        ),
        migrations.AlterField(
            model_name='drow',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Taxi_Manager.driver'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='drivers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Taxi_Manager.driver'),
        ),
    ]
