# Generated by Django 3.1.3 on 2021-04-13 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0022_auto_20210413_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='taxi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Taxi_Manager.taxi'),
        ),
    ]
