# Generated by Django 3.1.3 on 2021-04-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0023_auto_20210413_0842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drowsiness',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='drivers',
        ),
    ]
