# Generated by Django 3.1.3 on 2021-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0025_auto_20210416_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='contact_no',
            field=models.BigIntegerField(error_messages={'unique': 'This phone number has already been registered.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has already been registered.'}, max_length=254, unique=True),
        ),
    ]
