# Generated by Django 3.1.3 on 2021-04-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taxi_Manager', '0028_auto_20210421_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
